"""Chat router: streaming responses via Amazon Bedrock."""

import json
import os

import boto3
from botocore.exceptions import BotoCoreError, NoCredentialsError

from fastapi import APIRouter
from fastapi.responses import JSONResponse, StreamingResponse

from backend.models import ChatRequest
from backend.services.chat_service import ChatService
from backend.services.data_service import data_service

router = APIRouter()

_NOT_LOADED = "Dataset not loaded. Load data first to enable context-aware chat."
_BEDROCK_UNAVAILABLE = (
    "Bedrock client could not be initialised. Check AWS credentials and region."
)

_REPORT_SYSTEM_PROMPT = """You are a clinical research scientist writing a formal laboratory/scientific report.
Given a conversation between a researcher and an AI assistant about HNSCC (Head and Neck Squamous Cell Carcinoma)
patient data analysis, generate a comprehensive scientific report in Markdown format.

The report MUST follow this structure:

# Patient Similarity Analysis Report

## Abstract
A concise 150-200 word summary of the analysis performed, key findings, and clinical implications.

## 1. Introduction
Brief background on HNSCC, the HANCOCK dataset, and the analytical approach used (morphological embeddings, ABMIL, composite similarity scoring).

## 2. Methods
### 2.1 Dataset
Describe the dataset used (slides, patients, embedding model).
### 2.2 Similarity Scoring
Explain the composite scoring: slide-level cosine similarity (α), tissue composition profiles (β), clinical metadata matching (γ).
### 2.3 Analysis Pipeline
Describe the steps performed based on the conversation (retrieval, UMAP, clustering, etc.).

## 3. Results
### 3.1 Patient Profile
Summarise the query patient's clinical characteristics if discussed.
### 3.2 Morphologically Similar Patients
Present the top matches with their composite scores and clinical features.
### 3.3 Visualisation
Describe any UMAP or clustering results if discussed.

## 4. Discussion
Interpret the findings clinically. Discuss HPV status, histologic type, staging implications. Note limitations.

## 5. Clinical Implications
Specific actionable insights — trial eligibility, treatment considerations, cohort comparisons.

## 6. Limitations
Data limitations, embedding quality caveats, what cannot be concluded.

## 7. Conclusion
2-3 sentence summary of the key takeaway.

---
*Generated by HANCOCK Patient Similarity Analysis System*
*Embeddings: H-optimus-0 (Bioptimus) | Aggregation: GatedAttentionABMIL | Dataset: HANCOCK HNSCC*

Use formal scientific language. Be specific about patient IDs, scores, and clinical values mentioned in the conversation.
Only include sections relevant to what was actually discussed. Do not fabricate data not present in the conversation.

IMPORTANT — figure placement: When the conversation includes chart images (provided as Figure 1, Figure 2, etc.),
reference them inline in the text at the exact point where they are discussed using the marker format:
[Figure N: title]
For example: "The histologic type distribution is shown in [Figure 1: Histologic Type — 21 patients]."
Do NOT group all figures at the end. Place each figure marker immediately after the sentence that discusses it."""


@router.post("/stream")
async def chat_stream(request: ChatRequest):
    """POST /api/chat/stream — stream tokens from Bedrock via SSE.

    - HTTP 409: dataset not loaded
    - HTTP 503: Bedrock client cannot be initialised
    """
    if not data_service.get_status().loaded:
        return JSONResponse({"detail": _NOT_LOADED}, status_code=409)

    try:
        boto3.client("bedrock-runtime", region_name=os.environ.get("AWS_DEFAULT_REGION", "us-west-2"))
    except (BotoCoreError, NoCredentialsError) as exc:
        return JSONResponse(
            {"detail": f"{_BEDROCK_UNAVAILABLE} ({exc})"},
            status_code=503,
        )

    service = ChatService()
    return StreamingResponse(
        service.stream_response(request.messages, request.app_context),
        media_type="text/event-stream",
    )


class _ReportRequest(ChatRequest):
    chart_messages: list = []


@router.post("/report")
async def generate_report(request: _ReportRequest):
    """POST /api/chat/report — stream a scientific report from the conversation as SSE."""
    if not data_service.get_status().loaded:
        return JSONResponse({"detail": _NOT_LOADED}, status_code=409)

    model_id = os.environ.get("BEDROCK_MODEL_ID", "us.anthropic.claude-sonnet-4-6")
    region = os.environ.get("AWS_DEFAULT_REGION", "us-west-2")

    try:
        client = boto3.client("bedrock-runtime", region_name=region)
    except (BotoCoreError, NoCredentialsError) as exc:
        return JSONResponse({"detail": f"{_BEDROCK_UNAVAILABLE} ({exc})"}, status_code=503)

    # Use chart_messages if provided (includes vision content), otherwise build from transcript
    if request.chart_messages:
        messages = request.chart_messages
    else:
        transcript_lines = []
        for msg in request.messages:
            role = "Researcher" if msg.role == "user" else "Assistant"
            transcript_lines.append(f"**{role}:** {msg.content}")
        transcript = "\n\n".join(transcript_lines)
        messages = [{"role": "user", "content": (
            "Based on the following conversation, generate a formal scientific report:\n\n"
            f"---\n{transcript}\n---"
        )}]

    def stream_report():
        try:
            response = client.invoke_model_with_response_stream(
                modelId=model_id,
                body=json.dumps({
                    "anthropic_version": "bedrock-2023-05-31",
                    "max_tokens": 4096,
                    "system": _REPORT_SYSTEM_PROMPT,
                    "messages": messages,
                }),
                contentType="application/json",
                accept="application/json",
            )
            for event in response["body"]:
                chunk = json.loads(event["chunk"]["bytes"])
                if chunk.get("type") == "content_block_delta":
                    delta = chunk.get("delta", {}).get("text", "")
                    if delta:
                        yield f"data: {json.dumps({'delta': delta})}\n\n"
            yield f"data: {json.dumps({'done': True})}\n\n"
        except Exception as exc:  # noqa: BLE001
            yield f"data: {json.dumps({'error': str(exc)})}\n\n"

    return StreamingResponse(stream_report(), media_type="text/event-stream")
