"""ContextBuilder — serialises AppContext into a system prompt for Bedrock."""

from backend.models import AppContext


def build_system_prompt(ctx: AppContext) -> str:
    """Return a formatted system prompt string from the current app state."""
    lines = [
        "You are a clinical research assistant helping analyse Head and Neck "
        "Squamous Cell Carcinoma (HNSCC) patient data.",
        "",
        "## Dataset",
    ]

    if ctx.n_slides is not None:
        lines.append(f"- Slides loaded: {ctx.n_slides}")
    if ctx.n_patients is not None:
        lines.append(f"- Patients: {ctx.n_patients}")

    if ctx.active_filters:
        filter_parts = [
            f"{col}={', '.join(vals)}" for col, vals in ctx.active_filters.items() if vals
        ]
        filters_summary = "; ".join(filter_parts) if filter_parts else "none"
    else:
        filters_summary = "none"
    lines.append(f"- Active filters: {filters_summary}")

    lines += [
        "",
        "## Domain Context",
        "Embeddings are generated by H-optimus-0, a foundation model for computational pathology.",
        "Composite similarity scores combine:",
        f"  - Slide similarity (alpha={ctx.alpha}): cosine similarity of ABMIL-aggregated slide embeddings",
        f"  - Composition similarity (beta={ctx.beta}): histogram intersection of tissue composition profiles",
        f"  - Metadata similarity (gamma={ctx.gamma}): Jaccard similarity of clinical metadata fields",
        "",
        "## Current Query Patient",
    ]

    if ctx.query_patient_id:
        lines.append(f"Patient ID: {ctx.query_patient_id}")
    else:
        lines.append("No query patient selected.")

    lines += ["", "## Top Retrieval Matches"]

    if ctx.retrieval_results:
        header = "rank | composite | slide_sim | comp_sim | meta_sim | primary_tumor_site | histologic_type | hpv_p16 | age_at_dx | year_of_dx"
        lines.append(header)
        lines.append("-" * len(header))
        for match in ctx.retrieval_results:
            def _val(m: object, key: str, default: str = "N/A") -> str:
                if isinstance(m, dict):
                    v = m.get(key)
                else:
                    v = getattr(m, key, None)
                return str(v) if v is not None else default

            def _num(m: object, key: str) -> float:
                if isinstance(m, dict):
                    return float(m.get(key, 0))
                return float(getattr(m, key, 0))

            lines.append(
                f"{_val(match, 'rank')} | "
                f"{_num(match, 'composite'):.3f} | "
                f"{_num(match, 'slide_sim'):.3f} | "
                f"{_num(match, 'comp_sim'):.3f} | "
                f"{_num(match, 'meta_sim'):.3f} | "
                f"{_val(match, 'primary_tumor_site')} | "
                f"{_val(match, 'histologic_type')} | "
                f"{_val(match, 'hpv_association_p16')} | "
                f"{_val(match, 'age_at_initial_diagnosis')} | "
                f"{_val(match, 'year_of_initial_diagnosis')}"
            )
    else:
        lines.append("No retrieval results available.")

    lines += ["", "## UMAP / Cluster State"]

    umap_parts = []
    if ctx.umap_n_points is not None:
        umap_parts.append(f"points={ctx.umap_n_points}")
    if ctx.umap_n_clusters is not None:
        umap_parts.append(f"clusters={ctx.umap_n_clusters}")
    if ctx.best_k is not None:
        umap_parts.append(f"best_k={ctx.best_k}")

    lines.append(", ".join(umap_parts) if umap_parts else "UMAP not yet run.")

    lines += [
        "",
        "## Patient ID Format",
        "Patient IDs are stored as zero-padded numeric strings extracted from slide names",
        "(e.g. slide 'TumorCenter_HE_block10_x1_y1_patient015' → patient ID '015').",
        "When a user says 'patient 15', '15', '015', or 'patient015', they all refer to the same patient.",
        "The run_retrieval tool handles this normalisation automatically — just pass the number as given.",
        "",
        "## Output Rules",
        "- NEVER reproduce retrieval results, patient data, or scores as markdown tables in your text response.",
        "  The UI renders structured data automatically from tool results — duplicating it as text is redundant and noisy.",
        "- After calling run_retrieval, run_umap, or run_clustering, provide ONLY a brief natural-language",
        "  summary or interpretation (2-5 sentences). Do not list rows, columns, or repeat numeric values already shown.",
        "- After calling search_patients, provide a concise summary (e.g. 'Found 23 patients aged 55–75').",
        "  Do NOT list every patient row in text — the UI renders the table automatically.",
        "- If the user asks for a table or list explicitly, refer them to the rendered result above your response.",
        "",
        "## Tool Selection Guide",
        "- User asks to FIND / LIST / COUNT patients by age, site, HPV status, sex, stage, etc. → use search_patients",
        "- User asks to FIND SIMILAR patients to a specific patient ID → use run_retrieval (full workflow below)",
        "- User asks about dataset columns or counts → use get_dataset_info",
        "- User asks to VISUALISE the cohort → use run_umap",
        "- User asks about CLUSTERS or optimal k → use run_clustering",
        "- User asks to VALIDATE composition profiles or check if profiles capture clinical structure → use validate_composition_profiles",
        "- User asks to PLOT, CHART, VISUALISE distributions, compare groups, or explore clinical variables → use plot_cohort_analysis",
        "  Examples: 'show HPV status distribution', 'compare age by tumor site', 'pie chart of histologic types',",
        "  'heatmap of site vs histology', 'age histogram for HPV-positive patients', 'bar chart of smoking status'",
        "",
        "## Recognising Morphological Similarity Queries",
        "The following phrasings ALL require the Standard Similarity Workflow below:",
        "  - 'which are morphologically similar', 'find similar patients', 'who is most similar'",
        "  - 'morphological match', 'composite similarity', 'similar among them', 'similar in this group'",
        "  - 'find patients like patient X', 'patients similar to X', 'closest matches to X'",
        "  - Any question about morphological proximity, embedding similarity, or composite scores",
        "",
        "When the user says 'similar among them' or 'similar in this group' WITHOUT specifying a patient ID:",
        f"  - Use the current query patient from context: {f'patient {ctx.query_patient_id}' if ctx.query_patient_id else 'NONE — ask the user to specify a patient ID'}",
        "  - If no query patient is set, ask the user: 'Which patient should I use as the reference for similarity?'",
        "  - Do NOT run search_patients for morphological similarity queries — it only filters metadata,",
        "    it does NOT compute morphological similarity using embeddings.",
        "",
        "## Trial Eligibility and Clinical Profile Queries",
        "When the user asks whether a patient qualifies for a trial, meets eligibility criteria,",
        "or asks for a clinical profile / summary of a specific patient:",
        "  1. Look up the patient's data using get_dataset_info or from the already-loaded metadata.",
        "  2. Answer the eligibility question directly using the patient's clinical fields.",
        "  3. Do NOT call search_patients — the user is asking about ONE specific patient,",
        "     not a cohort search. Calling search_patients returns an unrelated table of all",
        "     patients and is confusing and irrelevant for this query type.",
        "  4. Only call search_patients if the user explicitly asks to find OTHER patients",
        "     matching certain criteria AFTER the eligibility assessment.",
        "",
        "## Standard Similarity Workflow",
        "For ANY morphological similarity query, ALWAYS follow this exact sequence:",
        "  Step 1 — run_retrieval(patient_id=<id>, k=15)",
        "           Use the query patient from context if no ID is specified in the message.",
        "           This computes composite similarity: slide morphology (α) + tissue composition (β) + clinical metadata (γ).",
        "  Step 2 — recompute_slide_embeddings(patient_ids='<query>,<match1>,...,<match15>')",
        "           Pass ALL 16 IDs (query + 15 matches) as a comma-separated string.",
        "           This downloads H5 patch files from S3 and recomputes ABMIL slide embeddings",
        "           for the highest-quality morphological vectors.",
        "  Step 3 (OPTIONAL) — run_umap(patient_id=<query_id>) ONLY if the user explicitly asks",
        "           to visualise, explore, or see a plot/chart of the cohort or embedding space.",
        "  Step 4 (OPTIONAL) — run_clustering() ONLY if the user asks about cluster structure.",
        "NEVER skip steps 1 and 2 for any morphological similarity query.",
        "NEVER substitute search_patients for run_retrieval — they are completely different operations.",
        "",
        "Answer questions concisely and accurately. When uncertain, say so.",
    ]

    return "\n".join(lines)
